### ISSUE TITLE
Error when entering wrong password

### ISSUE THREAD

**Issue by carchaias** [MWStake/mediawiki-extensions-UserLoginLog#4]
If a USer enteres a wrong password I receive the following error on may Wiki

[W720NsOjOnlY@omgxEOkWQAAAA4] /aquanautwebwiki11205/index.php?title=Spezial:Anmelden&returnto=Hauptseite ConfigException from line 53 of /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/config/GlobalVarConfig.php: GlobalVarConfig::get: undefined option: 'ServerUser'

Backtrace:

#0 /home/www/sites/194.245.123.76/mediawiki-1.31.0/extensions/UserLoginLog/src/Hook.php(80): GlobalVarConfig->get(string)
#1 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/Hooks.php(177): MediaWiki\Extension\UserLoginLog\Hook::logError(FakeAuthTemplate)
#2 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/Hooks.php(205): Hooks::callHook(string, array, array, NULL)
#3 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/LoginSignupSpecialPage.php(831): Hooks::run(string, array)
#4 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/LoginSignupSpecialPage.php(664): LoginSignupSpecialPage->getFakeTemplate(Message, string)
#5 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/LoginSignupSpecialPage.php(557): LoginSignupSpecialPage->getAuthForm(array, string, Message, string)
#6 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/LoginSignupSpecialPage.php(370): LoginSignupSpecialPage->mainLoginForm(array, Message, string)
#7 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/SpecialPage.php(522): LoginSignupSpecialPage->execute(NULL)
#8 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/specialpage/SpecialPageFactory.php(568): SpecialPage->run(NULL)
#9 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/MediaWiki.php(288): SpecialPageFactory::executePath(Title, RequestContext)
#10 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/MediaWiki.php(861): MediaWiki->performRequest()
#11 /home/www/sites/194.245.123.76/mediawiki-1.31.0/includes/MediaWiki.php(524): MediaWiki->main()
#12 /home/www/sites/194.245.123.76/mediawiki-1.31.0/index.php(42): MediaWiki->run()
#13 {main}

In LocalSettings I have 
wfLoadExtension( 'UserLoginLog' );
$wgServerUser = 1;

**Comment by carchaias** [comment]
Ok, I installed the master and now it works.
